<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation and editing :)
* https://orbisius.com/products/wordpress-plugins/orbisius-child-theme-creator
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: https://codex.wordpress.org/Child_Themes#Using_functions.php
*
* When copying functions from the parent theme make sure you use function_exists( 'put_the_function_name_here' ) calls.
* Otherwise having functions with the same name will crash the site.
* Also when adding new functions do put prefix before the function names to ensure uniqueness.
*/

/**
 * Loads parent theme's style first and then child theme's style.css so you can override parent styles
 */

// ===========================

// ===========================
// Remove thb-app-css from loading
function child_remove_thb_app_css( $tag, $handle, $href, $media ) {
    if ( 'thb-app-css' === $handle ) {
        // Log in browser console
        echo "<script>console.log('child_remove_thb_app_css function ran: removed thb-app-css');</script>";
        return ''; // remove the CSS link
    }
    return $tag;
}
add_filter( 'style_loader_tag', 'child_remove_thb_app_css', 10, 4 );



// Add this to the TOP of your functions.php file
if (!class_exists('Single_Post_Walker_Nav_Menu')) {
    class Single_Post_Walker_Nav_Menu extends Walker_Nav_Menu {
        public function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0) {
            // Your custom navigation HTML here
            $output .= '<a href="' . esc_url($item->url) . '" class="px-4 py-2 text-sm font-medium text-gray-700 hover:text-wine-700 transition-colors">' . esc_html($item->title) . '</a>';
        }
    }
}
 



// ========================
 
// Add support for post thumbnails
add_theme_support('post-thumbnails');

// Register navigation menus
register_nav_menus(array(
    'primary' => __('Primary Menu', 'your-theme-textdomain'),
    'footer' => __('Footer Menu', 'your-theme-textdomain')
));

// Custom Walker for Navigation Menu
class Custom_Walker_Nav_Menu extends Walker_Nav_Menu {
    public function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0) {
        $classes = empty($item->classes) ? array() : (array) $item->classes;
        $class_names = join(' ', apply_filters('nav_menu_css_class', array_filter($classes), $item, $args));
        
        $is_current = in_array('current-menu-item', $classes) || in_array('current-category-ancestor', $classes);
        
        $output .= '<a href="' . esc_url($item->url) . '" class="px-4 py-2 text-sm font-medium ' . 
                   ($is_current ? 'text-wine-700 font-semibold' : 'text-gray-700 hover:text-wine-700') . 
                   ' transition-colors">' . esc_html($item->title) . '</a>';
    }
}

// Mobile menu fallback
function custom_mobile_menu_fallback() {
    ?>
    <ul class="space-y-4">
        <li><a href="<?php echo esc_url(home_url('/')); ?>" class="block py-3 text-lg font-medium text-gray-800">Home</a></li>
        <?php
        $categories = get_categories(array('hide_empty' => false));
        foreach ($categories as $category) {
            echo '<li><a href="' . esc_url(get_category_link($category->term_id)) . '" class="block py-3 text-lg font-medium text-gray-800">' . esc_html($category->name) . '</a></li>';
        }
        ?>
    </ul>
    <?php
}

// Register category sidebar
function register_category_sidebar() {
    register_sidebar(array(
        'name'          => __('Category Sidebar', 'your-theme-textdomain'),
        'id'            => 'category-sidebar',
        'description'   => __('Widgets in this area will be shown on category pages.', 'your-theme-textdomain'),
        'before_widget' => '<div class="sidebar-widget">',
        'after_widget'  => '</div>',
        'before_title'  => '<h3 class="sidebar-widget-title">',
        'after_title'   => '</h3>',
    ));
}
add_action('widgets_init', 'register_category_sidebar');

// Custom query for sorting
function custom_category_query($query) {
    if ($query->is_category() && $query->is_main_query() && !is_admin()) {
        if (isset($_GET['orderby'])) {
            switch ($_GET['orderby']) {
                case 'popular':
                    $query->set('meta_key', 'post_views_count');
                    $query->set('orderby', 'meta_value_num');
                    $query->set('order', 'DESC');
                    break;
                case 'oldest':
                    $query->set('orderby', 'date');
                    $query->set('order', 'ASC');
                    break;
                case 'title':
                    $query->set('orderby', 'title');
                    $query->set('order', 'ASC');
                    break;
                default:
                    $query->set('orderby', 'date');
                    $query->set('order', 'DESC');
            }
        }
    }
}
add_action('pre_get_posts', 'custom_category_query');


 
// =============================
// ....................tailwind-enque.................
function theme_scripts() {
    wp_enqueue_style(
        'tailwind-cdn',
        get_stylesheet_directory_uri() .'/assets/dist/css/output.css',
         array(),
        time()
    );

     

	   
    // $custom_config = "
    //     tailwind.config = {
    //         theme: {
    //             extend: {
    //                 colors: {
    //                     wine: {
    //                         50: '#fdf2f4',
    //                         100: '#fce7ea',
    //                         200: '#f9d0d9',
    //                         300: '#f4a9b8',
    //                         400: '#ec7691',
    //                         500: '#df4a6e',
    //                         600: '#c9285a',
    //                         700: '#a91d4a',
    //                         800: '#8d1b42',
    //                         900: '#781b3d',
    //                         950: '#430a1e',
    //                     },
    //                     cream: {
    //                         50: '#fefdf8',
    //                         100: '#fdfbf0',
    //                         200: '#fbf6e3',
    //                         300: '#f6edd1',
    //                         400: '#efdeb0',
    //                         500: '#e6cb8a',
    //                     },
    //                     gold: {
    //                         400: '#c9a962',
    //                         500: '#b8973d',
    //                         600: '#a17f2f',
    //                     }
    //                 },
    //                 fontFamily: {
    //                     'serif': ['Cormorant Garamond', 'Georgia', 'serif'],
    //                     'sans': ['DM Sans', 'system-ui', 'sans-serif'],
    //                 }
    //             }
    //         }
    //     };
    // ";
    // wp_add_inline_script('tailwind-cdn', $custom_config);




wp_enqueue_style(
        'custom-style',
        get_stylesheet_directory_uri() . '/assits/modern-style.css',
        array(),
        time()
    );
   wp_enqueue_script(
        'modern-js',
        get_stylesheet_directory_uri() . '/assits/modern.js',
        array(),
        time()
    );

}
add_action('wp_enqueue_scripts', 'theme_scripts', "wp_enqueue_script");


//////////////////////////

// function child_theme_scripts() {
//     wp_enqueue_style(
//         'modern-custom-style',
//         get_stylesheet_directory_uri() . '/assits/modern-style.css',
//         array(),
//         filemtime(get_stylesheet_directory() . '/assits/modern-style.css')
//     );
// }
// add_action('wp_enqueue_scripts', 'child_theme_scripts');

//////////////////////////////

// Calculate reading time
function reading_time() {
    $content = get_post_field('post_content', get_the_ID());
    $word_count = str_word_count(strip_tags($content));
    $reading_time = ceil($word_count / 200); // Assuming 200 words per minute
    
    return $reading_time;
}

// .................................

// ....................................................

function orbisius_ct_theissue_child_theme_child_theme_enqueue_styles() {
	global $wp_styles;

    $parent_style = 'orbisius_ct_theissue_child_theme_parent_style';
    $parent_base_dir = 'theissue';
	$child_dir_id = basename(get_stylesheet_directory());

	// WP enqueues the child style automatically. We want to dequeue it so we can load parent first and child theme's css later
	// We'll also append the last modified times for versions and for better cache clean up.
	if ( ! empty( $wp_styles->queue ) ) {
		$srch_arr = [
			$parent_base_dir,
			$parent_base_dir . '-style',
			$parent_base_dir . '_style',
			$child_dir_id,
			$child_dir_id . '-style',
			$child_dir_id . '_style',
		];

		foreach ( $wp_styles->queue as $registered_style_id ) {
			if ( in_array( $registered_style_id, $srch_arr ) ) {
				wp_dequeue_style( $registered_style_id );
				wp_deregister_style( $registered_style_id );
			}
		}
	}

    // We use last modified as version as it's a reliable way to tell when the file was modified so
    // the browser can load the new file if necessary and not use the cached version.
    $parent_ver = time();
    $parent_style_css_file = get_template_directory() . '/style.css';

    if (file_exists($parent_style_css_file)) {
    	$parent_ver = filemtime($parent_style_css_file);
    } else {
    	$v = wp_get_theme( $parent_base_dir )->get('Version');

    	if (!empty($v)) {
		    $parent_ver = $v;
	    }
    }

    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
	    $parent_ver
    );

    wp_enqueue_style( $parent_style . '_child_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        filemtime(get_stylesheet_directory() . '/style.css')
    );

	wp_enqueue_style( $parent_style . 'font-awesome',
        'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css',
        array(),
        filemtime(get_stylesheet_directory() . '/style.css')
    );
	

	// adding in child theme
	wp_enqueue_script('popper', 'https://unpkg.com/@popperjs/core@2', array('jquery'), '1.0', true);
	wp_enqueue_script('tippy', 'https://unpkg.com/tippy.js@6', array('jquery'), '1.0', true);
	wp_enqueue_script('custom-script-handle', get_stylesheet_directory_uri() . '/custom-script.js', array('jquery'), '1.0', true);
	wp_enqueue_script('ilwviatorpartnre', 'https://ilovewine.partner.viator.com/orion/partner/widget.js', array('jquery'), '1.0', true);
}

add_action( 'wp_enqueue_scripts', 'orbisius_ct_theissue_child_theme_child_theme_enqueue_styles', 25 );

function orbisius_ct_theissue_child_theme_example_function() {
    // put some code here
}
add_role( 'team', __( 'Team' ), array( 'read'         => true,  'edit_posts'   => true, ) );
add_role( 'senior', __( 'Senior' ), array( 'read'         => true, 'edit_posts'   => true, ) );
add_role( 'contributors', __( 'Contributors' ), array( 'read'         => true, 'edit_posts'   => true, ) );
add_role( 'events', __( 'Events' ), array( 'read'         => true, 'edit_posts'   => true, ) );
add_role( 'marketing', __( 'Marketing' ), array( 'read'         => true, 'edit_posts'   => true, ) );

add_action('pre_user_search', 'change_user_order');

function change_user_order($query) {

    $query->query_orderby = ' ORDER BY user_login DESC';
}



// User Role
function user_role_content($arg){
	 ob_start();
	?>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Amiri:ital,wght@0,400;0,700;1,400;1,700&display=swap');
    .grid-container {
    display: grid;
    grid-template-columns: 25% 25% 25%;
    column-gap: 40px;
    row-gap: 0;
  }
	a._grid_item img {
    height: 56vh;
    object-fit: cover;
    object-position: center;
    display: inline-block;
}
  ._grid_img {
    display:block;
    overflow:hidden;
    transition:all .3s linear;
    position: relative;
  }
  ._grid_item img{
    filter: grayscale(.8);
    transition:all .3s linear;
    width:100%;
  }
  ._grid_item:hover img{
      transform:scale(1.1);
      filter:unset;
      transition:all .3s linear;
  }
  ._grid_item svg{
      position: absolute;
	  right: 0;
	  bottom: 20px;
	  opacity: 0;
	  transition: all .3s linear;
	  width: 40px;
	  height: 40px;
  }
  ._grid_item:hover svg{
      right: 22px;
      opacity: 1;
  }
  ._grid_item h2{
    font-family: 'Amiri', serif !important;
    font-size: 26px;
    color: #000;
    text-align: left;
    letter-spacing: 0px;
    margin-top: 20px;
    margin-bottom: 0;
	  font-weight: 400;
  }
  ._grid_item p{
	  color:#000;
    font-family: 'Amiri', serif !important;
    font-size: 18px;
    font-weight: 400;
  }
	._grid_item:nth-child(n+1){
		margin-top:0;
	}
 	._grid_item:nth-child(n+2){
		margin-top:20px;
	}
	._grid_item:nth-child(n+3){
		margin-top:40px;
	}
	._grid_item:nth-child(n+5){
		margin-top:60px;
	}
	._grid_item:nth-child(n+6){
		margin-top:80px;
	}
	._grid_item:nth-child(n+8){
		margin-top:20px;
	}
	._grid_item:nth-child(n+9){
		margin-top:40px;
	}
	._grid_item:nth-child(n+11){
		margin-top:20px;
	}
	._grid_item:nth-child(n+12){
		margin-top:40px;
	}
	
	@media (max-width: 768px){
	.grid-container {
			display: grid;
			grid-template-columns: 46% 46%;
			column-gap: 20px;
			width: 90%;
			margin: 0 auto;
		}
		a._grid_item img {
			height: 26vh;
	}
}
	@media (max-width: 991px) and (min-width: 768px) {
	.grid-container {
			display: grid;
			width: 100%;
		}
		a._grid_item img {
			height: 36vh;
	}
}
</style>
<div class="grid-container">
	<?php
	$ids = explode (",", $arg['user_id']);
	foreach ($ids as $id) {
		  $u_id = trim($id);
		  $u_name = get_userdata($u_id)->display_name;
		  $u_dp = get_user_meta($u_id,'image')[0];
		  $img_url = wp_get_attachment_image_src($u_dp, 'full')[0];
		  $u_desig = get_user_meta($u_id,'label')[0];
		  $u_url = get_author_posts_url($u_id);
		if(!empty($u_name))
		{
	?>
	  <a href="<?php echo $u_url;?>" class="_grid_item">
		<div class="_grid_img">
		  <img src="<?php echo $img_url; ?>">
			  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><g id="profile_icon" data-name="profile icon" transform="translate(-1307.333 -2281.333)"><circle id="Ellipse_18" data-name="Ellipse 18" cx="24" cy="24" r="24" transform="translate(1307.333 2281.333)" fill="#390101"></circle><g id="arrow-up-left" transform="translate(1341.964 2305.499) rotate(135)"><path id="Path_3001" data-name="Path 3001" d="M0,.74A.74.74,0,0,1,.74,0h7.4a.74.74,0,0,1,0,1.48H1.48V8.138a.74.74,0,0,1-1.48,0Z" transform="translate(0.001 0.001)" fill="#fff" fill-rule="evenodd"></path><path id="Path_3002" data-name="Path 3002" d="M.217.217a.74.74,0,0,1,1.048,0L14.583,13.535a.741.741,0,1,1-1.048,1.048L.217,1.265a.74.74,0,0,1,0-1.048Z" fill="#fff" fill-rule="evenodd"></path></g></g></svg>
		</div>
		<h2><?php echo $u_name; ?></h2>
		<p><?php echo $u_desig; ?></p>
	</a>
<?php 
	}
}	
?>

</div>
<script>
	jQuery(document).ready(function($){
		
	});
</script>
<?php
$myvariable=ob_get_clean();
  return $myvariable;
}
add_shortcode('team_members', 'user_role_content');

// adding code for wordpress taxonomy term for viator



//  Add field on "Add New" term screen
function ilw_child_theme_add_term_embed_field_add($taxonomy) {
    ?>
    <div class="form-field term-embed-code-wrap">
        <label for="term_embed_code"><?php _e('Embed Code', 'ilw_child_theme'); ?></label>
        <textarea name="term_embed_code" id="term_embed_code" rows="5" style="width:100%;"></textarea>
        <p class="description"><?php _e('Add your custom HTML or embed code here (e.g., iframe, video, etc.).', 'ilw_child_theme'); ?></p>
    </div>
    <?php
}
add_action('category_add_form_fields', 'ilw_child_theme_add_term_embed_field_add');
add_action('post_tag_add_form_fields', 'ilw_child_theme_add_term_embed_field_add');


function ilw_child_theme_add_term_embed_field($term) {
    $value = get_term_meta($term->term_id, 'term_embed_code', true);
    ?>
    <tr class="form-field">
        <th scope="row" valign="top"><label for="term_embed_code"><?php _e('Embed Code', 'mytheme'); ?></label></th>
        <td>
            <textarea name="term_embed_code" id="term_embed_code" rows="6" style="width:100%;"><?php echo esc_textarea($value); ?></textarea>
            <p class="description"><?php _e('Add your custom HTML or embed code here (e.g., iframe, video, etc.).', 'mytheme'); ?></p>
        </td>
    </tr>
    <?php
}
add_action('category_edit_form_fields', 'ilw_child_theme_add_term_embed_field');
add_action('post_tag_edit_form_fields', 'ilw_child_theme_add_term_embed_field');
// You can also add your custom taxonomy here, e.g.:
// add_action('your_taxonomy_edit_form_fields', 'ilw_child_theme_add_term_embed_field');


/**
 * Save the embed code when the term is updated.
 */
function ilw_child_theme_save_term_embed_field($term_id) {
    if (isset($_POST['term_embed_code'])) {
        update_term_meta($term_id, 'term_embed_code', wp_kses_post($_POST['term_embed_code']));
    }
}
add_action('created_category', 'ilw_child_theme_save_term_embed_field');
add_action('edited_category', 'ilw_child_theme_save_term_embed_field');

add_action('created_post_tag', 'ilw_child_theme_save_term_embed_field');
add_action('edited_post_tag', 'ilw_child_theme_save_term_embed_field');